In [1]:
#To begin with, have to import numpy as np

import numpy as np #np is short for numpy, it just saves us time to in commands

## Introduction to Numpy DataTypes & Attributes
- *Numpy main datatype is ndarray, everything you see in numpy is most likely ndarray* and it's called **N-Dimensional Array.**
- An array is simply any list of numbers and N-dimensional means almost any shape we can think of.

In [11]:
#Create first numpy array

a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [12]:
#Let's check it's datatype

type(a1)

numpy.ndarray

In [20]:
#Create some more arrays

a2 = np.array([[1, 2.0, 3.3],
              [4.0, 5.0, 6.5]])

a3 = np.array([[[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]],
                  
                  [[10, 11, 12],
                   [13, 14, 15],
                   [16, 17, 18]]])

In [21]:
#Print a2 
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [22]:
#Print a3
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [23]:
# Some of the arributes, associated with Numpys, we can check the shapes for the arrays we performed before:

a1.shape #it shows (3,) because it only shows column for this shape, since we only have one row. or sometimes (1,3)

(3,)

In [24]:
#Check the anatomy of a2
a2.shape

(2, 3)

In [25]:
#check the anatomy of a3
a3.shape

(2, 3, 3)

In [26]:
#Try number of dimensions, ndim stands for number of dimensions
a1.ndim, a2.ndim, a3.ndim

#Depending on how big our dta is, these dimensions keep growing

(1, 2, 3)

In [27]:
#Find out the datatypes 
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [29]:
a1.size, a2.size, a3.size #Size attribute tells how many many total elements we have got in our array

(3, 6, 18)

In [30]:
type(a1), type(a2), type(a3) #ndarray is universal datatype

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

### Create a dataframe from *Numpy* array

In [34]:
#We will import panda library

import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5