In [90]:
#To begin with, have to import numpy as np

import numpy as np #np is short for numpy, it just saves us time to in commands

## Introduction to Numpy DataTypes & Attributes
- *Numpy main datatype is ndarray, everything you see in numpy is most likely ndarray* and it's called **N-Dimensional Array.**
- An array is simply any list of numbers and N-dimensional means almost any shape we can think of.

In [91]:
#Create first numpy array

a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [92]:
#Let's check it's datatype

type(a1)

numpy.ndarray

In [93]:
#Create some more arrays

a2 = np.array([[1, 2.0, 3.3],
              [4.0, 5.0, 6.5]])

a3 = np.array([[[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]],
                  
                  [[10, 11, 12],
                   [13, 14, 15],
                   [16, 17, 18]]])

In [94]:
#Print a2 
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [95]:
#Print a3
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [96]:
# Some of the arributes, associated with Numpys, we can check the shapes for the arrays we performed before:

a1.shape #it shows (3,) because it only shows column for this shape, since we only have one row. or sometimes (1,3)

(3,)

In [97]:
#Check the anatomy of a2
a2.shape

(2, 3)

In [98]:
#check the anatomy of a3
a3.shape

(2, 3, 3)

In [99]:
#Try number of dimensions, ndim stands for number of dimensions
a1.ndim, a2.ndim, a3.ndim

#Depending on how big our dta is, these dimensions keep growing

(1, 2, 3)

In [100]:
#Find out the datatypes 
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [101]:
a1.size, a2.size, a3.size #Size attribute tells how many many total elements we have got in our array

(3, 6, 18)

In [102]:
type(a1), type(a2), type(a3) #ndarray is universal datatype

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

### Create a dataframe from *Numpy* array

In [103]:
#We will import panda library

import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## Create Numpy arrays

In [104]:
#1-Dimensional Numpy array
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [105]:
sample_array.dtype

dtype('int64')

In [106]:
ones = np.ones((1, 2, 3))

In [107]:
ones

array([[[1., 1., 1.],
        [1., 1., 1.]]])

#### In Machine Learning, Zeros are kind of like a placeholder array:
- In Machine Learning, sometimes we want to fill an array with some initial data or the data we don't know yet, so you create zeros to figure out the shapes of data we're working with.

In [108]:
# We can try with np.zeros

zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [109]:
#arange array: It will have start, stop and skip. For example code below, start at 0, finish at 10 but skip 2 for intervals

range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [110]:
#Random. randtint array: If we don't know any numbers, and we want random fill in an array, we use random array:

random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[2, 9, 4, 6, 1],
       [0, 1, 1, 8, 2],
       [9, 5, 6, 0, 3]])

In [111]:
#Let's check the size of our random array, which will give us number of elements in the array
random_array.size

15

In [112]:
#We can check the shape of it, as we asked for 3 x 5 (which means 3 rows and 5 columns shape)
random_array.shape

(3, 5)

In [113]:
#Totally random array .random

random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.86199936, 0.59028378, 0.67426006],
       [0.30375406, 0.25111261, 0.21695607],
       [0.58458583, 0.98544796, 0.48809561],
       [0.8765126 , 0.944892  , 0.98722491],
       [0.93401598, 0.2408063 , 0.15676742]])

In [114]:
#Let's check the shape for random_array_2
random_array_2.shape

(5, 3)

In [115]:
#There's another random array which can sometimes get confusing in in Numpy, it's .rand() 

random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.27359119, 0.9151579 , 0.40355689],
       [0.14959616, 0.78713652, 0.15704568],
       [0.63161278, 0.95592184, 0.82020686],
       [0.21627274, 0.6002433 , 0.68535913],
       [0.80998771, 0.7974721 , 0.79796367]])

### Let's create random seed: which are also known as Pseudo-random numbers. 
- When Numpy generates random numbers, it's actually suedo random numbers.
- Through out our Machine learning journey, whereever we come across random numbers array, we will see
```python
np.random.seed()
```
Description about .seed():
*The seed function in NumPy (np.random.seed()) is like setting a starting point for generating random numbers. Think of it as a recipe - if you use the same seed, you'll get the same sequence of random numbers every time.*

In [116]:
np.random.seed(seed=1) # seed = it could be any number from 0
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[5, 8, 9],
       [5, 0, 0],
       [1, 7, 6],
       [9, 2, 4],
       [5, 2, 4]])

In [117]:
#We can check the shape of random_array_4 and size parameter is actually the shape of our arrays
random_array_4.shape

(5, 3)

In [118]:
#Another example with .seed()

np.random.seed(7)
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

### Key Takeaways:
- The number we see Numpy generating randomly are not actually random, they are Pseudo numbers

In [119]:
#If we don't have random.seed() in our code, in the backend, numbers are generating with random seeds.

## Different ways of *Viewing arrays and Matrices* 

In [120]:
# .unique() : Returns the sorted unique value.

np.unique(random_array_4)

array([0, 1, 2, 4, 5, 6, 7, 8, 9])

In [121]:
a1

array([1, 2, 3])

In [122]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [123]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [124]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[3, 5, 8, 8, 7],
         [5, 0, 0, 2, 8],
         [9, 6, 4, 9, 7],
         [3, 3, 8, 3, 0]],

        [[1, 0, 0, 6, 7],
         [7, 9, 3, 0, 7],
         [7, 7, 0, 5, 4],
         [3, 1, 3, 1, 3]],

        [[4, 3, 1, 9, 5],
         [9, 1, 2, 3, 2],
         [2, 5, 7, 3, 0],
         [9, 9, 3, 4, 5]]],


       [[[3, 0, 4, 8, 6],
         [7, 2, 7, 3, 8],
         [6, 6, 5, 6, 5],
         [7, 1, 5, 4, 4]],

        [[9, 9, 0, 6, 2],
         [6, 8, 2, 4, 1],
         [6, 1, 5, 1, 6],
         [9, 8, 6, 5, 9]],

        [[7, 5, 4, 9, 6],
         [8, 1, 5, 5, 8],
         [3, 7, 7, 9, 4],
         [7, 5, 9, 6, 2]]]])

In [125]:
a4.shape

(2, 3, 4, 5)

In [126]:
a4.ndim #number of dimensions

4

In [135]:
#Get the first four numbers of inner most arrays
a4[:, :, :, :4]

array([[[[3, 5, 8, 8],
         [5, 0, 0, 2],
         [9, 6, 4, 9],
         [3, 3, 8, 3]],

        [[1, 0, 0, 6],
         [7, 9, 3, 0],
         [7, 7, 0, 5],
         [3, 1, 3, 1]],

        [[4, 3, 1, 9],
         [9, 1, 2, 3],
         [2, 5, 7, 3],
         [9, 9, 3, 4]]],


       [[[3, 0, 4, 8],
         [7, 2, 7, 3],
         [6, 6, 5, 6],
         [7, 1, 5, 4]],

        [[9, 9, 0, 6],
         [6, 8, 2, 4],
         [6, 1, 5, 1],
         [9, 8, 6, 5]],

        [[7, 5, 4, 9],
         [8, 1, 5, 5],
         [3, 7, 7, 9],
         [7, 5, 9, 6]]]])

### Manipulating Arrays
- **Arithmetic** : It's a fancy word for basic maths equations

In [136]:
a1

array([1, 2, 3])

In [141]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [142]:
a1 + ones #Adding the 2 arrays

array([2., 3., 4.])

In [143]:
a1 - ones #Subtracting the 2 arrays

array([0., 1., 2.])

In [144]:
a1 * ones #Multiply the 2 arrays

array([1., 2., 3.])

In [148]:
a1

array([1, 2, 3])

In [149]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [150]:
a1 * a2 #Multiply

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [151]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [153]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [155]:
# Reshape a2 to be (2,1,3) or (2,3,1)
result = a2.reshape(2,1,3) * a3
result

array([[[  1. ,   4. ,   9.9],
        [  4. ,  10. ,  19.8],
        [  7. ,  16. ,  29.7]],

       [[ 40. ,  55. ,  78. ],
        [ 52. ,  70. ,  97.5],
        [ 64. ,  85. , 117. ]]])

### Performing some python arithemic functions

In [158]:
a1 / ones #Division

array([1., 2., 3.])

In [161]:
a2 / a1 #division

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

In [163]:
a2 // a1 #double slash in python, is for floor division, it removes the decimals from the values (rounds down)

array([[1., 1., 1.],
       [4., 2., 2.]])

In [165]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [164]:
a2 ** 2 # it's the power, power of a2 here is 2, that means a2 * a2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

### Numpy has it's own arithemic methods, which one to use python or numpy, depends on our workflow

In [167]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [169]:
np.add(a1, ones)

array([2., 3., 4.])

In [170]:
#modulo in python, which show us the remainder
a1 % 2

array([1, 0, 1])

In [172]:
a1 / 2

array([0.5, 1. , 1.5])

In [173]:
#it gives us the exponential of the values
np.exp(a1) 

array([ 2.71828183,  7.3890561 , 20.08553692])

In [174]:
np.exp(a2)

array([[  2.71828183,   7.3890561 ,  27.11263892],
       [ 54.59815003, 148.4131591 , 665.14163304]])

In [175]:
np.log(a1) #this help to see the log of an array, very useful in machine learning projects

array([0.        , 0.69314718, 1.09861229])