In [1]:
#To begin with, have to import numpy as np

import numpy as np #np is short for numpy, it just saves us time to in commands

## Introduction to Numpy DataTypes & Attributes
- *Numpy main datatype is ndarray, everything you see in numpy is most likely ndarray* and it's called **N-Dimensional Array.**
- An array is simply any list of numbers and N-dimensional means almost any shape we can think of.

In [11]:
#Create first numpy array

a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [12]:
#Let's check it's datatype

type(a1)

numpy.ndarray

In [20]:
#Create some more arrays

a2 = np.array([[1, 2.0, 3.3],
              [4.0, 5.0, 6.5]])

a3 = np.array([[[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]],
                  
                  [[10, 11, 12],
                   [13, 14, 15],
                   [16, 17, 18]]])

In [21]:
#Print a2 
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [22]:
#Print a3
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [23]:
# Some of the arributes, associated with Numpys, we can check the shapes for the arrays we performed before:

a1.shape #it shows (3,) because it only shows column for this shape, since we only have one row. or sometimes (1,3)

(3,)

In [24]:
#Check the anatomy of a2
a2.shape

(2, 3)

In [25]:
#check the anatomy of a3
a3.shape

(2, 3, 3)

In [26]:
#Try number of dimensions, ndim stands for number of dimensions
a1.ndim, a2.ndim, a3.ndim

#Depending on how big our dta is, these dimensions keep growing

(1, 2, 3)

In [27]:
#Find out the datatypes 
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [29]:
a1.size, a2.size, a3.size #Size attribute tells how many many total elements we have got in our array

(3, 6, 18)

In [30]:
type(a1), type(a2), type(a3) #ndarray is universal datatype

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

### Create a dataframe from *Numpy* array

In [34]:
#We will import panda library

import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## Create Numpy arrays

In [36]:
#1-Dimensional Numpy array
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [37]:
sample_array.dtype

dtype('int64')

In [40]:
ones = np.ones((1, 2, 3))

In [41]:
ones

array([[[1., 1., 1.],
        [1., 1., 1.]]])

#### In Machine Learning, Zeros are kind of like a placeholder array:
- In Machine Learning, sometimes we want to fill an array with some initial data or the data we don't know yet, so you create zeros to figure out the shapes of data we're working with.

In [44]:
# We can try with np.zeros

zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [45]:
#arange array: It will have start, stop and skip. For example code below, start at 0, finish at 10 but skip 2 for intervals

range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [53]:
#Random. randtint array: If we don't know any numbers, and we want random fill in an array, we use random array:

random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[7, 6, 7, 6, 0],
       [3, 1, 5, 3, 4],
       [9, 5, 9, 0, 8]])

In [49]:
#Let's check the size of our random array, which will give us number of elements in the array
random_array.size

15

In [50]:
#We can check the shape of it, as we asked for 3 x 5 (which means 3 rows and 5 columns shape)
random_array.shape

(3, 5)

In [56]:
#Totally random array .random

random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.6660524 , 0.3976064 , 0.1769514 ],
       [0.61757264, 0.47901413, 0.4322862 ],
       [0.91339375, 0.4104531 , 0.71072974],
       [0.16465009, 0.56544893, 0.09274836],
       [0.17155785, 0.65609752, 0.25934992]])

In [57]:
#Let's check the shape for random_array_2
random_array_2.shape

(5, 3)

In [59]:
#There's another random array which can sometimes get confusing in in Numpy, it's .rand() 

random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.49053862, 0.61021172, 0.66456301],
       [0.24890998, 0.73439168, 0.9825875 ],
       [0.57879912, 0.65965929, 0.59177006],
       [0.38226766, 0.39756596, 0.64664341],
       [0.20274903, 0.29696728, 0.64274854]])

In [ ]:
#Let's create random seed: which are also known as Pseudo-random numbers. 
#When Numpy generates random numbers, it's actually suedo random numbers

